In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/nlp-getting-started/sample_submission.csv
/kaggle/input/nlp-getting-started/train.csv
/kaggle/input/nlp-getting-started/test.csv


In [2]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras import layers
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import pandas as pd


In [3]:
df_train = pd.read_csv('/kaggle/input/nlp-getting-started/train.csv')
df_test  = pd.read_csv('/kaggle/input/nlp-getting-started/test.csv')
df_train.columns,df_test.columns



(Index(['id', 'keyword', 'location', 'text', 'target'], dtype='object'),
 Index(['id', 'keyword', 'location', 'text'], dtype='object'))

In [4]:
df_train.shape,df_test.shape

((7613, 5), (3263, 4))

In [5]:
X = df_train.drop(['target'],axis=1)
Y = df_train['target']

In [6]:
X = X['text']

In [7]:
X

0       Our Deeds are the Reason of this #earthquake M...
1                  Forest fire near La Ronge Sask. Canada
2       All residents asked to 'shelter in place' are ...
3       13,000 people receive #wildfires evacuation or...
4       Just got sent this photo from Ruby #Alaska as ...
                              ...                        
7608    Two giant cranes holding a bridge collapse int...
7609    @aria_ahrary @TheTawniest The out of control w...
7610    M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...
7611    Police investigating after an e-bike collided ...
7612    The Latest: More Homes Razed by Northern Calif...
Name: text, Length: 7613, dtype: object

In [8]:
# Segreation of the target and feature (Independent and dependent data)
X.shape,Y.shape

((7613,), (7613,))

In [9]:
X_test_final =df_test['text']

In [10]:
X_test_final.shape

(3263,)

In [11]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.1, random_state=123)

In [12]:
x_train

1500    catastrophic-fallen-angel: reveillertm: macabr...
4487    Cont'd- #Sinjar: referring to a 40-pg document...
6971    I liked a @YouTube video http://t.co/0h7OUa1pn...
3256    #RaheelSharif is manifesting how one RIGHT man...
1369    @marcoarment Middle of winter in Sydney we hav...
                              ...                        
4060    #HeartDisease U.S. Forest Service says spendin...
1346    I will never support looting or the burning of...
3454    holy crap @KingMyth1999 my phone just exploded...
7533    Wreckage 'Conclusively Confirmed' as From MH37...
3582    APD investigating fatal shooting of 3 year old...
Name: text, Length: 6851, dtype: object

In [13]:
y_test.unique(),y_train.unique()#x_train.unique(),x_test.unique()

(array([0, 1]), array([0, 1]))

In [14]:
tokenizer = Tokenizer(num_words=1000)
tokenizer.fit_on_texts(X)
xtrain= tokenizer.texts_to_sequences(x_train)
xtest= tokenizer.texts_to_sequences(x_test) 


In [15]:
xtest,xtrain

([[613, 125, 549, 125, 3, 1, 2, 3, 1, 2],
  [4, 765, 247, 481, 55, 3, 1, 2, 53, 121],
  [49, 26, 40, 34, 9, 51, 245, 6, 356],
  [772, 5, 93],
  [850, 391, 8, 3, 1, 2, 53],
  [60, 537, 5, 128, 7, 492, 6, 980, 400, 608, 3, 1, 2],
  [37, 810, 26, 34, 601, 20, 5, 691, 23, 1, 2],
  [284, 416, 3, 1, 2, 3, 1, 2],
  [12, 187, 423, 543, 3, 1, 2, 53, 10, 632, 21, 282],
  [102, 11, 12, 390],
  [111, 7, 34, 7, 50, 5, 518, 934],
  [265, 5, 52, 12, 494, 6, 647, 9, 4, 18, 5, 113],
  [93, 203, 8, 75, 269, 3, 1, 2],
  [26, 6, 5, 299, 255, 137, 100, 13, 4, 19, 187, 9, 7, 162, 288, 86, 62, 5],
  [34, 5, 12, 8, 5, 224, 36, 212, 95],
  [149, 21, 600, 50, 712, 31, 20, 5, 467, 6, 226, 5, 550, 3, 1, 2],
  [458, 236, 13, 5, 6, 23, 1, 2],
  [675, 13, 19, 353, 666, 58, 3, 1, 2, 3, 1, 2],
  [142,
   7,
   663,
   66,
   661,
   54,
   79,
   361,
   142,
   538,
   20,
   4,
   192,
   377,
   8,
   560,
   949,
   3,
   1,
   2],
  [48, 158, 7, 346, 912, 159, 199, 11, 10, 186, 25, 57, 12, 23, 1, 2],
  [37, 726, 

In [16]:
maxlen = 30
xtrain =pad_sequences(xtrain,padding='post', maxlen=maxlen)
xtest = pad_sequences(xtest,padding='post', maxlen=maxlen)

In [17]:
xtrain,xtest

(array([[510,  10,  26, ...,   0,   0,   0],
        [  7,   5, 361, ...,   0,   0,   0],
        [ 10, 311,   5, ...,   0,   0,   0],
        ...,
        [ 15, 446,  34, ...,   0,   0,   0],
        [376, 736, 737, ...,   0,   0,   0],
        [192, 647,   8, ...,   0,   0,   0]], dtype=int32),
 array([[613, 125, 549, ...,   0,   0,   0],
        [  4, 765, 247, ...,   0,   0,   0],
        [ 49,  26,  40, ...,   0,   0,   0],
        ...,
        [643,  60,  95, ...,   0,   0,   0],
        [ 27,   6,  10, ...,   0,   0,   0],
        [290,  28,   5, ...,   0,   0,   0]], dtype=int32))

In [18]:
vocab_size=len(tokenizer.word_index)+1
embedding_dim=50
model=Sequential()
model.add(layers.Embedding(input_dim=vocab_size,output_dim=embedding_dim,input_length=maxlen))
model.add(layers.LSTM(units=50,return_sequences=True))
model.add(layers.LSTM(units=10))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(8))
model.add(layers.Dense(1, activation="sigmoid"))
model.compile(optimizer="adam", loss="binary_crossentropy",metrics=['accuracy'])
model.summary()

2022-08-11 15:27:58.120564: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 30, 50)            1135050   
_________________________________________________________________
lstm (LSTM)                  (None, 30, 50)            20200     
_________________________________________________________________
lstm_1 (LSTM)                (None, 10)                2440      
_________________________________________________________________
dropout (Dropout)            (None, 10)                0         
_________________________________________________________________
dense (Dense)                (None, 8)                 88        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 9         
Total params: 1,157,787
Trainable params: 1,157,787
Non-trainable params: 0
______________________________________________

In [19]:
model.fit(xtrain,y_train, epochs=20, batch_size=16, verbose=False)

2022-08-11 15:27:58.878373: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


In [20]:
loss, acc = model.evaluate(xtrain, y_train, verbose=False)
print("Training Accuracy: ", acc)
loss, acc = model.evaluate(xtest, y_test, verbose=False)
print("Test Accuracy: ", acc)

Training Accuracy:  0.9356298446655273
Test Accuracy:  0.7769029140472412


In [21]:
ypred=model.predict(xtest)


In [22]:
ypred[ypred>0.5]=1 
ypred[ypred<=0.5]=0 
cm = confusion_matrix(y_test, ypred)

In [23]:
cm

array([[387,  59],
       [111, 205]])

In [24]:
tokenizer = Tokenizer(num_words=1000)
tokenizer.fit_on_texts(X_test_final)
x_test_n = tokenizer.texts_to_sequences(X_test_final)



In [25]:
x_test_n

[[34, 567, 5, 985, 135, 100],
 [272, 53, 247, 11, 743, 890, 429],
 [75, 11, 5, 130, 42, 22, 891, 23, 986, 4, 568, 10, 481, 101, 43],
 [295],
 [273, 815, 235, 7, 9],
 [892, 59, 48, 247],
 [744, 92, 212, 46, 124, 102, 198, 679],
 [987, 54, 23, 14],
 [67, 5, 614],
 [430, 89],
 [33, 10, 87, 29, 893],
 [87, 66, 20],
 [33, 87, 431, 38, 20],
 [67, 45],
 [988],
 [296, 11, 522, 615, 57, 42, 30, 22, 296, 3, 1, 2],
 [39, 14, 13, 522],
 [680, 989, 681, 522, 3, 1, 2],
 [390, 297, 30, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2],
 [15, 745, 522, 2, 745, 522],
 [126, 522, 27],
 [106, 141, 522, 17, 3, 1, 2, 49],
 [35,
  5,
  523,
  62,
  39,
  169,
  84,
  351,
  9,
  432,
  18,
  16,
  746,
  59,
  48,
  894,
  352,
  55,
  11,
  53,
  56,
  353,
  4,
  248,
  522],
 [28,
  186,
  522,
  5,
  616,
  119,
  125,
  298,
  320,
  8,
  895,
  321,
  28,
  186,
  353,
  3,
  1,
  2],
 [682, 522, 3, 1, 2],
 [4,
  7,
  990,
  8,
  4,
  17,
  15,
  165,
  353,
  522,
  4,
  187,
  127,
  354,
  524,
  31,
  4,
  991,

In [26]:
maxlen = 30
x_test_pad =pad_sequences(x_test_n,padding='post', maxlen=maxlen)

In [27]:
x_test_pad.shape

(3263, 30)

In [28]:
yprednew=model.predict(x_test_pad)


In [29]:
yprednew

array([[0.99983066],
       [0.4039168 ],
       [0.1033642 ],
       ...,
       [0.19705555],
       [0.9985064 ],
       [0.5474148 ]], dtype=float32)

In [30]:
yprednew[yprednew>0.5]=1 
yprednew[yprednew<=0.5]=0 


In [31]:
yprednew.shape

(3263, 1)

In [32]:
# creating submission.csv to publish results
submission = pd.read_csv('/kaggle/input/nlp-getting-started/sample_submission.csv')
submission['target'] = yprednew
submission.to_csv('submission.csv',index=False)